(function(){
'use strict';
let overlay=null,resolveCurrent=null;
function ensure(){
  if(overlay)return overlay;
  const style=document.createElement('style');style.textContent=`
  .appi-dialog-overlay{position:fixed;inset:0;z-index:30000;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(20,22,38,.54);backdrop-filter:blur(10px)}.appi-dialog-overlay[hidden]{display:none!important}.appi-dialog-card{position:relative;width:min(100%,410px);max-height:min(86vh,86dvh);display:flex;flex-direction:column;padding:25px 23px 22px;border-radius:25px;background:rgba(255,255,255,.98);box-shadow:0 25px 80px rgba(25,27,58,.34);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;text-align:center}.appi-dialog-icon{width:58px;height:58px;margin:0 auto 10px;border-radius:18px;display:grid;place-items:center;background:linear-gradient(135deg,#5b8def,#8b63e8);color:#fff;font-size:26px;box-shadow:0 9px 23px rgba(91,112,210,.24)}.appi-dialog-card h2{margin:0 0 7px;color:#292938;font-size:20px}.appi-dialog-message{margin:0 0 17px;color:#686977;font-size:13px;line-height:1.5;white-space:pre-wrap;overflow-y:auto;-webkit-overflow-scrolling:touch;overscroll-behavior:contain;flex:1 1 auto;min-height:0}.appi-dialog-input{width:100%;min-height:48px;margin:0 0 14px;padding:12px 13px;border:1px solid rgba(80,90,130,.15);border-radius:14px;background:#f8f9ff;color:#292938;font:inherit;font-size:14px;outline:none}.appi-dialog-input:focus{border-color:#5b8def;box-shadow:0 0 0 3px rgba(91,141,239,.11)}.appi-dialog-choices{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:0 0 15px}.appi-dialog-choices.two{grid-template-columns:repeat(2,1fr);max-width:330px;margin-left:auto;margin-right:auto}.appi-dialog-choices button.active{background:linear-gradient(135deg,#5b8def,#8b63e8);color:#fff;border-color:transparent;box-shadow:0 6px 16px rgba(91,112,210,.28)}.appi-dialog-choices button{min-height:43px;border:1px solid rgba(91,141,239,.15);border-radius:12px;background:rgba(91,141,239,.08);color:#3d63c9;font:inherit;font-size:12px;font-weight:850;cursor:pointer}.appi-dialog-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.appi-dialog-actions.one{grid-template-columns:1fr}.appi-dialog-actions button{min-height:46px;border:0;border-radius:13px;font:inherit;font-size:13px;font-weight:900;cursor:pointer}.appi-dialog-cancel{background:rgba(80,90,130,.09);color:#666776}.appi-dialog-ok{background:linear-gradient(135deg,#5b8def,#8b63e8);color:#fff}.appi-dialog-ok.danger{background:linear-gradient(135deg,#d9534f,#ff6b6b)}body.dark .appi-dialog-card{background:#25273a}body.dark .appi-dialog-card h2{color:#f2f2f7}body.dark .appi-dialog-message{color:#b8b9c5}body.dark .appi-dialog-input{background:#1d1f31;color:#f2f2f7;border-color:rgba(255,255,255,.1)}@media(max-width:430px){.appi-dialog-card{padding:22px 17px 18px}.appi-dialog-choices{grid-template-columns:1fr}}
  `;document.head.appendChild(style);
  overlay=document.createElement('div');overlay.className='appi-dialog-overlay';overlay.hidden=true;overlay.innerHTML='<div class="appi-dialog-card" role="dialog" aria-modal="true"><div class="appi-dialog-icon" id="appiDialogIcon">✓</div><h2 id="appiDialogTitle">APPI</h2><div class="appi-dialog-message" id="appiDialogMessage"></div><input class="appi-dialog-input" id="appiDialogInput"><div class="appi-dialog-choices" id="appiDialogChoices"></div><div class="appi-dialog-actions" id="appiDialogActions"><button type="button" class="appi-dialog-cancel" id="appiDialogCancel">Cancelar</button><button type="button" class="appi-dialog-ok" id="appiDialogOk">Aceptar</button></div></div>';document.body.appendChild(overlay);return overlay;
}
function close(value){if(!overlay)return;overlay.hidden=true;const done=resolveCurrent;resolveCurrent=null;if(done)done(value)}
function show(options={}){
  ensure();if(resolveCurrent)close(null);
  const title=document.getElementById('appiDialogTitle'),message=document.getElementById('appiDialogMessage'),icon=document.getElementById('appiDialogIcon'),input=document.getElementById('appiDialogInput'),choices=document.getElementById('appiDialogChoices'),actions=document.getElementById('appiDialogActions'),cancel=document.getElementById('appiDialogCancel'),ok=document.getElementById('appiDialogOk');
  title.textContent=options.title||'APPI';message.textContent=options.message||'';icon.textContent=options.icon||'✓';input.hidden=!options.input;choices.hidden=!options.choices;choices.innerHTML='';cancel.hidden=options.cancel===false;ok.hidden=options.ok===false;cancel.textContent=options.cancelText||'Cancelar';ok.textContent=options.okText||'Aceptar';ok.classList.toggle('danger',!!options.danger);actions.classList.toggle('one',options.cancel===false||options.ok===false);
  if(options.input){input.type=options.inputType||'text';input.value=options.initial||'';input.placeholder=options.placeholder||''}
  if(options.choices){choices.classList.toggle('two',options.choices.length===2);for(const item of options.choices){const button=document.createElement('button');button.type='button';button.textContent=item.label;button.classList.toggle('active',options.active!==undefined&&item.value===options.active);button.onclick=()=>close(item.value);choices.appendChild(button)}}
  overlay.hidden=false;return new Promise(resolve=>{resolveCurrent=resolve;cancel.onclick=()=>close(null);ok.onclick=()=>close(options.input?input.value:true);overlay.onclick=event=>{if(event.target===overlay&&options.dismissible!==false)close(null)};input.onkeydown=event=>{if(event.key==='Enter')ok.click();if(event.key==='Escape'&&options.dismissible!==false)cancel.click()};setTimeout(()=>{if(options.input)input.focus();else ok.focus()},30)});
}
const api={
  alert:(message,options={})=>show({...options,message,cancel:false,icon:options.icon||'✓'}),
  confirm:(message,options={})=>show({...options,message,icon:options.icon||'?',dismissible:options.dismissible!==false}).then(Boolean),
  prompt:(message,initial='',options={})=>show({...options,message,input:true,initial,icon:options.icon||'✎'}),
  choose:(message,choices,options={})=>show({...options,message,choices,icon:options.icon||'◉',ok:false,cancel:true})
};
window.APPIDialog=api;
window.alert=message=>{api.alert(String(message),{title:'APPI',icon:'!'})};
})();
